srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    mtu: 9214
    description: leaf1
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.0/31
  - name: ethernet-1/2
    admin-state: enable
    mtu: 9214
    description: leaf2
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.2/31
  - name: ethernet-1/3
    admin-state: enable
    mtu: 9214
    description: leaf3
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.4/31
  - name: ethernet-1/4
    admin-state: enable
    mtu: 9214
    description: leaf4
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.6/31
  - name: ethernet-1/5
    admin-state: enable
    mtu: 9214
    description: leaf5
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.8/31
  - name: ethernet-1/6
    admin-state: enable
    mtu: 9214
    description: leaf6
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.10/31
  - name: ethernet-1/7
    admin-state: enable
    mtu: 9214
    description: leaf7
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.12/31
  - name: ethernet-1/8
    admin-state: enable
    mtu: 9214
    description: leaf8
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.1.14/31
  - name: loopback0
    admin-state: enable
    subinterface:
      - index: 0
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 10.0.250.1/32

srl_nokia-network-instance:network-instance:
  - name: default
    admin-state: enable
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0
      - name: ethernet-1/4.0
      - name: ethernet-1/5.0
      - name: ethernet-1/6.0
      - name: ethernet-1/7.0
      - name: ethernet-1/8.0
      - name: loopback0.0
    protocols:
      srl_nokia-bgp:bgp:
        autonomous-system: 65000
        router-id: 10.0.250.1
        afi-safi:
          - afi-safi-name: ipv4-unicast
            admin-state: enable
        group:
          - group-name: evpn
            admin-state: enable
        neighbor:
          - peer-address: 10.0.1.1
            peer-as: 65001
          - peer-address: 10.0.1.3
            peer-as: 65001
          - peer-address: 10.0.1.5
            peer-as: 65002
          - peer-address: 10.0.1.7
            peer-as: 65002
          - peer-address: 10.0.1.9
            peer-as: 65003
          - peer-address: 10.0.1.11
            peer-as: 65003
          - peer-address: 10.0.1.13
            peer-as: 65004
          - peer-address: 10.0.1.15
            peer-as: 65004
          - peer-address: 10.0.250.11
            peer-as: 65001
            peer-group: evpn
          - peer-address: 10.0.250.12
            peer-as: 65001
            peer-group: evpn
          - peer-address: 10.0.250.13
            peer-as: 65002
            peer-group: evpn
          - peer-address: 10.0.250.14
            peer-as: 65002
            peer-group: evpn
          - peer-address: 10.0.250.15
            peer-as: 65003
            peer-group: evpn
          - peer-address: 10.0.250.16
            peer-as: 65003
            peer-group: evpn
          - peer-address: 10.0.250.17
            peer-as: 65004
            peer-group: evpn
          - peer-address: 10.0.250.18
            peer-as: 65004
            peer-group: evpn
